### ISSUE TITLE
About the training dataset

### ISSUE THREAD

**Issue by david20571015** [850552586/Latent-To-Latent#9]
Thanks for your implementation of Latent to Latent.

I wonder if the authors mention which dataset they used for training the attribute transformer network (denoted as `f` in the paper)?

I can only find the dataset for training the attribute regression network in section 4.1

**Comment by 850552586** [comment]
I can’t remember the details,but it seems like that they used the persenal data which only open to internal .

**Comment by david20571015** [comment]
Got it, thanks for your reply!
